### ISSUE TITLE
 Termination message: Model was proven to be infeasible.

### ISSUE THREAD

**Issue by sarahalzaabi** [mchlshort/DECO2#2]
Hello, 

I tried running the software using cbc solver however, it showed that the model was infeasible for the min emissions objective.
<img width="714" alt="Screenshot 2022-07-08 at 2 28 46 PM" src="https://user-images.githubusercontent.com/108939146/178001540-84b8ae3f-0ae9-412b-b71e-2d632a64d962.png">

Also, when running the code for min budget, it worked, however, when I looked at the results in the Optimal_Decarbonization_User_Interface sheet and the Industry_User_Interafce_v1 both were the same so which one should the results go into?

**Comment by Purusothmn** [comment]
Hi. Please try to run the model again as I did not encounter issues for both objective functions. 

As for the worksheet, you may want to use the Base_User_Interface as that is a smaller case study. Additionally, you should not be getting same results for the files mentioned as the case studies are very different to each other. 

Optimal_Decarbonisation_User_Interface is for the power generation sector
Industry_User_Interface is for the chemical industry sector. 

Both those files differ in terms of the available technologies and plants.
